export const data = [
    {
        name: "ASPCA",
        cured_condition_eligible: "6 months",
        dental: true,
        food: true,
        unique: "",
        death_coverage: false,
        deductable: "$100",
        cancellation: "30-day money-back guarantee",
        reviews: "bad",
        reimbursement_rate: "90%",
        reimbursement_max: "$5000",
        quote: "$53",
        signup_fee: "none"
    },
    {
        name: "Pet Plan",
        cured_condition_eligible: "12 months",
        dental: true,
        food: true,
        unique: "E-vet visits",
        death_coverage: false,
        deductable: "$250",
        cancellation: "30-day money-back guarantee",
        reviews: "good",
        reimbursement_rate: "90%",
        reimbursement_max: "$5000",
        quote: "$45",
        signup_fee: "none"
    },
    {
        name: "PetWatch",
        cured_condition_eligible: "N/A",
        dental: false,
        food: true,
        unique: "Discount if already a pre-existing customer with their microchip services",
        death_coverage: false,
        deductable: "$100",
        cancellation: "None",
        reviews: "good",
        reimbursement_rate: "80%",
        reimbursement_max: "$5000",
        quote: "$46",
        signup_fee: "none"
    },
    {
        name: "Embrace",
        cured_condition_eligible: "12 months",
        dental: true,
        food: true,
        unique: "RX food covered via FSA",
        death_coverage: false,
        deductable: "$200, vanishing",
        cancellation: "30-day money-back guarantee",
        reviews: "",
        reimbursement_rate: "90%",
        reimbursement_max: "$5000",
        quote: "$62",
        signup_fee: "$25"
    },
    {
        name: "Figo",
        cured_condition_eligible: "Yes, but unknown timeframe",
        dental: false,
        food: false,
        unique: "Includes a full social media app and telehealth",
        death_coverage: true,
        deductable: "",
        cancellation: "30-day money-back guarantee",
        reviews: "good",
        reimbursement_rate: "90%",
        reimbursement_max: "Unlimited",
        quote: "$30",
        signup_fee: "none"
    },
    {
        name: "Nationwide",
        cured_condition_eligible: "6 months",
        dental: false,
        food: true,
        unique: "Covers exotic pets, and provides e-vet visits",
        death_coverage: false,
        deductable: "$250",
        cancellation: "None",
        reviews: "",
        reimbursement_rate: "Fixed by specific diagnosis",
        reimbursement_max: "Fixed by specific diagnosis",
        quote: "$48",
        signup_fee: "Unknown"
    },
    {
        name: "Pet First",
        cured_condition_eligible: "Yes, but unknown timeframe",
        dental: false,
        food: false,
        unique: "",
        death_coverage: false,
        deductable: "$50-$100",
        cancellation: "14-day money-back guarantee",
        reviews: "mixed",
        reimbursement_rate: "90%",
        reimbursement_max: "$5000",
        quote: "$38-$45",
        signup_fee: "Unknown"
    },
    {
        name: "Spot",
        cured_condition_eligible: "6 months",
        dental: true,
        food: true,
        unique: "",
        death_coverage: false,
        deductable: "$100",
        cancellation: "30-day money-back guarantee",
        reviews: "",
        reimbursement_rate: "90%",
        reimbursement_max: "$5000",
        quote: "$46",
        signup_fee: "None"
    },
    {
        name: "Healthy Paws",
        cured_condition_eligible: "Unknown",
        dental: false,
        food: false,
        unique: "",
        death_coverage: false,
        deductable: "$750",
        cancellation: "30-day money-back guarantee",
        reviews: "",
        reimbursement_rate: "70%",
        reimbursement_max: "Unlimited",
        quote: "$28",
        signup_fee: "$25"
    },
    {
        name: "Trupanion",
        cured_condition_eligible: "Unknown",
        dental: false,
        food: false,
        unique: "Pays directly",
        death_coverage: false,
        deductable: "",
        cancellation: "30-day money-back guarantee",
        reviews: "",
        reimbursement_rate: "",
        reimbursement_max: "",
        quote: "",
        signup_fee: "$35"
    },
    {
        name: "TrustedPals",
        cured_condition_eligible: "As soon as declared cured by vet, no wait time",
        dental: true,
        food: true,
        unique: "",
        death_coverage: true,
        deductable: "$100",
        cancellation: "",
        reviews: "",
        reimbursement_rate: "100%",
        reimbursement_max: "$8000",
        quote: "$52",
        signup_fee: "$21"
    },
    {
        name: "Pumpkin",
        cured_condition_eligible: "6 months",
        dental: true,
        food: true,
        unique: "",
        death_coverage: false,
        deductable: "$250",
        cancellation: "30-day money-back guarantee",
        reviews: "",
        reimbursement_rate: "90%",
        reimbursement_max: "$7000",
        quote: "$58",
        signup_fee: "None"
    },
    {
        name: "Prudent Pet",
        cured_condition_eligible: "Unknown",
        dental: true,
        food: false,
        unique: "No covereage for traveling veterinary/any house calls",
        death_coverage: true,
        deductable: "$250",
        cancellation: "30-day money-back guarantee",
        reviews: "",
        reimbursement_rate: "90%",
        reimbursement_max: "Unlimited",
        quote: "$48",
        signup_fee: ""
    },
    {
        name: "Pets Best",
        cured_condition_eligible: "None",
        dental: false,
        food: false,
        unique: "",
        death_coverage: false,
        deductable: "",
        cancellation: "30-day money-back guarantee",
        reviews: "",
        reimbursement_rate: "",
        reimbursement_max: "",
        quote: "",
        signup_fee: ""
    }0
]